version: '2'
services:
  healthcheck:
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
    image: hcwdocker.service.tieto.com/rancher/healthcheck:v0.1.0
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
